const Manu = [
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 2,
    name: "Barger",
    image: "Image/bargar.jpg",
    cetagory: "snackes",
    price: "10$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 3,
    name: "Chart",
    image: "Image/chart.jpg",
    cetagory: "snackes",
    price: "5$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 4,
    name: "Pasta",
    image: "Image/pasta.jpg",
    cetagory: "Lunch",
    price: "10$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 5,
    name: "Thali",
    image: "Image/main_course.jpg",
    cetagory: "lunch",
    price: "150$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 6,
    name: "Poje",
    image: "Image/poje.jpg",
    cetagory: "breakfast",
    price: "5$",
    description: "This Food is cooking on sejoan noodels",
  },
];
