const Manu = [
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 2,
    name: "Barger",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
  {
    id: 1,
    name: "Noodles",
    image: "Image/noodle.jpg",
    cetagory: "dinner",
    price: "50$",
    description: "This Food is cooking on sejoan noodels",
  },
];
